#!/usr/bin/env bash
# charter-common.sh — Shared utilities for the Charter extension
# All scripts source this file for common paths and helpers.
set -euo pipefail

# ── Paths ───────────────────────────────────────────────────────────────────
# PROJECT_ROOT must be set by the caller (defaults to current directory)
PROJECT_ROOT="${PROJECT_ROOT:-.}"

# Extension install directory. The scripts live here, but this directory is
# managed by `specify extension` and is wiped/reset on install, update, and
# removal (only *-config.yml files survive). NEVER store persistent data here.
CHARTER_EXT_DIR="${PROJECT_ROOT}/.specify/extensions/charter"

# Persistent data directory. Lives OUTSIDE the extension install dir so it
# survives `specify extension update|remove` and `specify init --here --force`
# (Spec Kit only overwrites its own template files, never unknown directories).
# This directory is meant to be committed to git.
CHARTER_DATA_DIR="${PROJECT_ROOT}/.specify/charter"
CHARTER_CONFIG="${CHARTER_DATA_DIR}/config.yml"
CHARTER_STATE="${CHARTER_DATA_DIR}/state.yml"
CHARTER_SNAPSHOTS_DIR="${CHARTER_DATA_DIR}/snapshots"
CHARTER_BACKUPS_DIR="${CHARTER_DATA_DIR}/backups"
# Disposable cache (gitignored) — cloned git registries, downloads, etc.
CHARTER_CACHE_DIR="${CHARTER_DATA_DIR}/.cache"
CONSTITUTION_PATH="${PROJECT_ROOT}/.specify/memory/constitution.md"

# ── Helpers ─────────────────────────────────────────────────────────────────

# Print an error message to stderr and exit
die() {
  echo "❌ ERROR: $*" >&2
  exit 1
}

# Print a warning message to stderr
warn() {
  echo "⚠️  WARNING: $*" >&2
}

# Print an info message
info() {
  echo "ℹ️  $*"
}

# Ensure a directory exists
ensure_dir() {
  mkdir -p "$1"
}

# Ensure the persistent data directory exists and carries a .gitignore that
# excludes the disposable cache from version control. Everything else in
# CHARTER_DATA_DIR (config.yml, state.yml, snapshots/, backups/) is meant to be
# committed.
ensure_charter_data_dir() {
  ensure_dir "$CHARTER_DATA_DIR"
  local gitignore="${CHARTER_DATA_DIR}/.gitignore"
  if [[ ! -f "$gitignore" ]]; then
    cat > "$gitignore" <<'GITIGNORE'
# Disposable cache (cloned registries, downloads) — do not version.
.cache/
GITIGNORE
  fi
}

# Validate a package path to prevent path traversal attacks
# Rejects absolute paths and paths containing ".."
# Usage: validate_package_path "<PACKAGE_PATH>"
# Returns 0 if valid, dies with error if invalid
validate_package_path() {
  local path="$1"
  if [[ "$path" == /* || "$path" == *..* ]]; then
    die "Invalid package path: $path (absolute paths and '..' traversal not allowed)"
  fi
}

# Check if a value looks like a git URL
is_git_url() {
  local val="$1"
  case "$val" in
    git@*|https://*.git|http://*.git|https://github.com/*|https://gitlab.com/*|git://*)
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

# Read a YAML field using grep/sed (no yq dependency for portability)
# Usage: yaml_field "file.yml" "field_name"
yaml_field() {
  local file="$1" field="$2"
  # "|| true": grep exits 1 on no match, which under pipefail+set -e would abort the caller
  grep -E "^${field}:" "$file" 2>/dev/null | head -1 | sed "s/^${field}:[[:space:]]*//" | sed 's/^"\(.*\)"$/\1/' | sed "s/^'\(.*\)'$/\1/" || true
}

# Read a YAML list field — returns one item per line (simple flat lists only)
# Usage: yaml_list "file.yml" "field_name"
yaml_list() {
  local file="$1" field="$2"
  # "|| true": grep exits 1 on no match, which under pipefail+set -e would abort the caller
  # POSIX character classes rather than "\s": BSD/macOS sed does not support
  # "\s", so the list-syntax strip silently no-ops there and every entry is
  # returned as `  - "name"` instead of `name`. This matches yaml_field above,
  # which already uses [[:space:]].
  sed -n "/^${field}:/,/^[^ ]/p" "$file" | grep -E '^[[:space:]]*-[[:space:]]' | sed 's/^[[:space:]]*-[[:space:]]*//' | sed 's/^"\(.*\)"$/\1/' | sed "s/^'\(.*\)'$/\1/" || true
}

# Get the registry path from config
get_registry() {
  if [[ -f "$CHARTER_CONFIG" ]]; then
    yaml_field "$CHARTER_CONFIG" "registry"
  else
    echo ".charter"
  fi
}

# Get the "distributed sub-constitutions" enabled flag from config (default false)
get_distributed_enabled() {
  if [[ -f "$CHARTER_CONFIG" ]]; then
    local v
    v="$(yaml_field "$CHARTER_CONFIG" "distributed_sub_constitutions")"
    [[ "$v" == "true" ]] && echo "true" || echo "false"
  else
    echo "false"
  fi
}

# Write the charter config file.
# Usage: write_config <REGISTRY> <REGISTRY_TYPE> [DISTRIBUTED_FLAG]
write_config() {
  local registry="$1" reg_type="$2" distributed="${3:-false}"
  ensure_charter_data_dir
  cat > "$CHARTER_CONFIG" <<EOF
# Charter Extension Configuration
# Generated by /speckit.charter.config

# Registry source
registry: "${registry}"

# Auto-detected registry type
registry_type: "${reg_type}"

# Distributed sub-constitutions: search monorepo packages for
# "<package>/.charter/constitution.md" files and offer them for selection.
distributed_sub_constitutions: ${distributed}
EOF
}

# Get the registry type from config (or auto-detect)
get_registry_type() {
  local registry
  registry="$(get_registry)"
  if is_git_url "$registry"; then
    echo "git"
  else
    echo "directory"
  fi
}

# Resolve registry to a local path (clone if git, return path if directory)
# Sets REGISTRY_LOCAL_PATH on success
resolve_registry_path() {
  local registry registry_type
  registry="$(get_registry)"
  registry_type="$(get_registry_type)"

  if [[ "$registry_type" == "git" ]]; then
    REGISTRY_LOCAL_PATH="${CHARTER_CACHE_DIR}/registry"
    # Clone or update
    if [[ -d "${REGISTRY_LOCAL_PATH}/.git" ]]; then
      git -C "$REGISTRY_LOCAL_PATH" fetch --quiet origin 2>/dev/null || die "Failed to fetch registry: $registry"
      git -C "$REGISTRY_LOCAL_PATH" reset --quiet --hard origin/HEAD 2>/dev/null || true
    else
      rm -rf "$REGISTRY_LOCAL_PATH"
      git clone --quiet --depth 1 "$registry" "$REGISTRY_LOCAL_PATH" 2>/dev/null || die "Failed to clone registry: $registry"
    fi
  else
    # Resolve relative paths against project root
    if [[ "$registry" == /* ]]; then
      REGISTRY_LOCAL_PATH="$registry"
    else
      REGISTRY_LOCAL_PATH="${PROJECT_ROOT}/${registry}"
    fi
  fi
}
